'''
    Initial Layout


    :copyright: (C) 2014 by the SaltStack Team, see AUTHORS for more details.
    :license: Apache 2.0, see LICENSE for more details.


    Revision ID: 230f2e9a95c3
    Revises: None
    Create Date: 2014-01-06 18:14:45.004743

'''

# revision identifiers, used by Alembic.
revision = '230f2e9a95c3'
down_revision = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.sql import table


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('groups',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(length=30), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table('accounts',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('login', sa.String(length=100), nullable=True),
        sa.Column('name', sa.String(length=100), nullable=True),
        sa.Column('email', sa.String(length=254), nullable=True),
        sa.Column('access_token', sa.String(length=100), nullable=True),
        sa.Column('avatar_url', sa.String(length=2000), nullable=True),
        sa.Column('last_login', sa.DateTime(), nullable=False),
        sa.Column('register_date', sa.DateTime(), nullable=False),
        sa.Column('locale', sa.String(length=10), nullable=True),
        sa.Column('timezone', sa.String(length=25), nullable=True),
        sa.Column('datetime_format', sa.String(length=50), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_accounts_access_token', 'accounts', ['access_token'], unique=True)
    op.create_table('build_servers',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('address', sa.String(length=256), nullable=False),
        sa.Column('username', sa.String(length=128), nullable=False),
        sa.Column('access_token', sa.String(length=128), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('address')
    )
    op.create_table('privileges',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(length=50), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('name')
    )
    op.create_table('group_privileges',
        sa.Column('group_id', sa.Integer(), nullable=True),
        sa.Column('privilege_id', sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ),
        sa.ForeignKeyConstraint(['privilege_id'], ['privileges.id'], ),
        sa.PrimaryKeyConstraint()
    )
    op.create_table('account_privileges',
        sa.Column('account_id', sa.Integer(), nullable=False),
        sa.Column('privilege_id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
        sa.ForeignKeyConstraint(['privilege_id'], ['privileges.id'], ),
        sa.PrimaryKeyConstraint()
    )
    op.create_table('group_accounts',
        sa.Column('group_id', sa.Integer(), nullable=True),
        sa.Column('account_id', sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
        sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ),
        sa.PrimaryKeyConstraint()
    )
    ### end Alembic commands ###

    # Insert Group Privileges data
    privileges = table('privileges',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(length=50), nullable=False),
    )
    # Insert Some Data
    groups = table('groups',
        sa.Column('id', sa.Integer(), nullable=False, autoincrement=True),
        sa.Column('name', sa.String(length=30), nullable=True),
    )
    group_privileges = table('group_privileges',
        sa.Column('group_id', sa.Integer(), nullable=True),
        sa.Column('privilege_id', sa.Integer(), nullable=True),
    )

    # Insert Some Data
    op.bulk_insert(
        privileges, [
            {'name': 'administrator'},
            {'name': 'manager'},
            {'name': 'fork_pusher'},
            {'name': 'pr_full_builds'},
            {'name': 'pr_min_builds'},
            {'name': 'registered'}
        ]
    )
    op.bulk_insert(
        groups, [
            {'name': 'Administrators'},
            {'name': 'Managers'},
            {'name': 'Forked Repository Push Builds'},
            {'name': 'Pull-Requests Full Builds'},
            {'name': 'Pull-Requests Minimal Builds'},
            {'name': 'Registered'}
        ]
    )
    op.bulk_insert(
        group_privileges, [
            {'group_id': 1, 'privilege_id': 1},
            {'group_id': 2, 'privilege_id': 2},
            {'group_id': 3, 'privilege_id': 3},
            {'group_id': 4, 'privilege_id': 4},
            {'group_id': 5, 'privilege_id': 5},
            {'group_id': 6, 'privilege_id': 6},
        ]
    )


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('group_accounts')
    op.drop_table('account_privileges')
    op.drop_table('group_privileges')
    op.drop_table('privileges')
    op.drop_table('build_servers')
    op.drop_index('ix_accounts_access_token', 'accounts')
    op.drop_table('accounts')
    op.drop_table('groups')
    ### end Alembic commands ###
